name: hire_me
description: A new Flutter project.
# Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  go_router: ^13.1.0
  animate_do: ^3.3.4
  flare_flutter: ^3.0.2
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.1.1
  cloud_firestore: ^4.8.2
  firebase_core: any
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  fluttertoast: ^8.2.2
  loading_animation_widget: ^1.2.1
  heroicons: 0.7.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  material_floating_search_bar_2: ^0.5.0
  flutter_launcher_icons: ^0.13.1
  http:
  dio:
  equatable: ^2.0.5


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 600